### ISSUE TITLE
export problem with large files

### ISSUE THREAD

**Issue by uvius** [cisocrgroup/PoCoTo#2]
exporting a large file (more than 3600 subimages) leads to a timeout:

```
[INFO] 2016-10-05 20:33:26,440 - [java.lang.Class] PoCoTo version: 16.01.3
[INFO] 2016-10-05 20:33:26,451 - [java.lang.Class] Setup logging base dir '/home/uvius/.ocrcorrection/dev'
[INFO] 2016-10-05 20:33:27,462 - [jav.gui.main.MainController] Programmstart
[INFO] 2016-10-05 20:58:21,884 - [jav.gui.main.MainController] MainTopComponent # Document changed
[INFO] 2016-10-05 20:58:23,412 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0001__R0001r__ro357564684568544579089__000__r1__TextRegion__heading.tif, 0.400000)
[INFO] 2016-10-05 20:58:30,539 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0001__R0001r__ro357564684568544579089__001__r2__TextRegion__page-number.tif, 0.400000)
[INFO] 2016-10-05 20:58:37,466 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0001__R0001r__ro357564684568544579089__002__r5__TextRegion__paragraph.tif, 0.400000)
[INFO] 2016-10-05 20:58:43,084 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0001__R0001r__ro357564684568544579089__003__r8__TextRegion__heading.tif, 0.400000)
[INFO] 2016-10-05 20:58:46,199 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0001__R0001r__ro357564684568544579089__004__r10__TextRegion__paragraph.tif, 0.400000)
[INFO] 2016-10-05 20:58:50,115 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0001__R0001r__ro357564684568544579089__005__r11__TextRegion__paragraph.tif, 0.400000)
[INFO] 2016-10-05 20:59:12,314 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0001__R0001r__ro357564684568544579089__006__r12__TextRegion__paragraph.tif, 0.400000)
[INFO] 2016-10-05 20:59:20,706 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0002__R0001v__ro357564684568544579089__000__r1__TextRegion__heading.tif, 0.400000)
[INFO] 2016-10-05 20:59:24,953 - [jav.gui.image.CompleteImageTopComponent] loadImage(/home/uvius/data/OCR/Kallimachos/Itf954/ocro-tif/DE-20__I_t_f_954__0002__R0001v__ro357564684568544579089__001__r2__TextRegion__paragraph.tif, 0.400000)
[INFO] 2016-10-05 21:00:34,646 - [jav.gui.main.MainController] profiler_service_url: 'http://localhost:8080/axis2/services/ProfilerWebService'
[INFO] 2016-10-05 21:00:42,644 - [jav.gui.main.MainController] profiler_service_url: 'http://localhost:8080/axis2/services/ProfilerWebService'
[INFO] 2016-10-05 21:00:42,722 - [jav.gui.main.MainController$DocumentProfiler] exporting document ...
[ERROR] 2016-10-05 21:01:16,643 - Exception:
java.sql.SQLException: Login timeout
    at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:208)
    at jav.correctionBackend.Document.getTokenByIndex(Document.java:1351)
    at jav.correctionBackend.PageIterator.next(Document.java:2322)
    at jav.correctionBackend.PageIterator.next(Document.java:2274)
    at jav.correctionBackend.OcrXmlExporter.export(OcrXmlExporter.java:57)
    at jav.correctionBackend.Document.exportAsDocXML(Document.java:1604)
    at jav.gui.main.MainController$DocumentProfiler.run(MainController.java:1117)
    at jav.gui.main.MainController$DocumentProfiler.run(MainController.java:1066)
    at org.netbeans.modules.progress.ui.RunOffEDTImpl$ProgressBackgroundRunner.runBackground(RunOffEDTImpl.java:486)
    at org.netbeans.modules.progress.ui.AbstractWindowRunner.call(AbstractWindowRunner.java:108)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
[ERROR] 2016-10-05 21:01:16,646 - [jav.gui.main.MainController$DocumentProfiler] profiling error: null
[ERROR] 2016-10-05 21:08:57,934 - [jav.correctionBackend.SpreadIndexDocument] SQLException: Login timeout
```

**Comment by finkf** [comment]
fixed with 5e20240d176921c52c44fc90b03d8cfcb30252d4
